//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nippori.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nippori.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 会
        ///同
        ///事
        ///自
        ///社
        ///発
        ///者
        ///地
        ///業
        ///方
        ///新
        ///場
        ///員
        ///立
        ///開
        ///手
        ///力
        ///問
        ///代
        ///明
        ///動
        ///京
        ///目
        ///通
        ///言
        ///理
        ///体
        ///田
        ///主
        ///題
        ///意
        ///不
        ///作
        ///用
        ///度
        ///強
        ///公
        ///持
        ///野
        ///以
        ///思
        ///家
        ///世
        ///多
        ///正
        ///安
        ///院
        ///心
        ///界
        ///教
        ///文
        ///元
        ///重
        ///近
        ///考
        ///画
        ///海
        ///売
        ///知
        ///道
        ///集
        ///別
        ///物
        ///使
        ///品
        ///計
        ///死
        ///特
        ///私
        ///始
        ///朝
        ///運
        ///終
        ///台
        ///広
        ///住
        ///真
        ///有
        ///口
        ///少
        ///町
        ///料
        ///工
        ///建
        ///空
        ///急
        ///止
        ///送
        ///切
        ///転
        ///研
        ///足
        ///究
        ///楽
        ///起
        ///着
        ///店
        ///病
        ///質
        ///待
        ///試
        ///族
        ///銀
        ///早
        ///映
        ///親
        ///験
        ///英
        ///医
        ///仕
        ///去
        ///味
        ///写
        ///字
        ///答
        ///夜
        ///音
        ///注
        ///帰
        ///古
        ///歌
        ///買
        ///悪
        ///図
        ///週
        ///室
        ///歩
        ///風
        ///紙
        ///黒
        ///花
        ///春
        ///赤
        ///青
        ///館
        ///屋
        ///色
        ///走
        ///秋
        ///夏
        ///習
        ///駅
        ///洋
        ///旅
        ///服
        ///夕
        ///借
        ///曜
        ///飲
        ///肉
        ///貸
        ///堂
        ///鳥
        ///飯
        ///勉
        ///冬
        ///昼
        ///茶
        ///弟
        ///牛
        ///魚
        ///兄
        ///犬
        ///妹
        ///姉
        ///漢
        ///.
        /// </summary>
        internal static string kanji_n4 {
            get {
                return ResourceManager.GetString("kanji_n4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 日
        ///一
        ///国
        ///人
        ///年
        ///大
        ///十
        ///二
        ///本
        ///中
        ///長
        ///出
        ///三
        ///時
        ///行
        ///見
        ///月
        ///後
        ///前
        ///生
        ///五
        ///間
        ///上
        ///東
        ///四
        ///今
        ///金
        ///九
        ///入
        ///学
        ///高
        ///円
        ///子
        ///外
        ///八
        ///六
        ///下
        ///来
        ///気
        ///小
        ///七
        ///山
        ///話
        ///女
        ///北
        ///午
        ///百
        ///書
        ///先
        ///名
        ///川
        ///千
        ///水
        ///半
        ///男
        ///西
        ///電
        ///校
        ///語
        ///土
        ///木
        ///聞
        ///食
        ///車
        ///何
        ///南
        ///万
        ///毎
        ///白
        ///天
        ///母
        ///火
        ///右
        ///読
        ///友
        ///左
        ///休
        ///父
        ///雨
        ///.
        /// </summary>
        internal static string kanji_n5 {
            get {
                return ResourceManager.GetString("kanji_n5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open_6529 {
            get {
                object obj = ResourceManager.GetObject("Open_6529", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
